## Übungen zur Lektion 2: Aggregatfunktionen mit der cia-Datenbank

In [2]:
import pandas as pd
import sqlite3
con = sqlite3.connect('../../data/cia.db')
df = pd.read_sql("SELECT * FROM cia", con)
len(df)

## Aufgaben

Aufgabe 1
Wie viele Länder enthält die cia-Datenbank?

In [3]:
df[["Name"]].nunique()

Name    234
dtype: int64

Aufgabe 2
Ermittle die Weltbevölkerung.

In [4]:
df[["Einwohner"]].sum()

Einwohner    6.079432e+09
dtype: float64

Aufgabe 3
Gib das Durchschnitts-Bruttoinlandsprodukt an.

In [6]:
df[["BIP"]].mean()

BIP    1.779868e+11
dtype: float64

Aufgabe 4
Wie groß sind Bevölkerung und Bruttoinlandsprodukt für ganz Europa?

In [20]:
df[["Einwohner","BIP"]][ df["Region"]=="Europa" ].sum()

Einwohner    5.844266e+08
BIP          9.516350e+12
dtype: float64

In [5]:
df[["Region","Name","Einwohner","BIP"]][df["Region"].str.contains("Europa", case = False)]

,Region,Name,Einwohner,BIP
1,Europa,Albanien,3490435.0,5.600000e+09
4,Europa,Andorra,66824.0,1.200000e+09
10,Osteuropa,Armenien,3344336.0,9.900000e+09
13,Europa,Österreich,8131111.0,1.906000e+11
14,Osteuropa,Azerbaijan,7748163.0,1.400000e+10
19,Osteuropa,Belarus,10366719.0,5.520000e+10
20,Europa,Belgien,10241506.0,2.434000e+11
26,Europa,Bosnien und Herzegovina,3835777.0,6.200000e+09
31,Europa,Bulgarien,7796694.0,3.490000e+10
53,Europa,Kroatien,4282216.0,2.390000e+10
56,Europa,Tschechische Republik,10272179.0,1.208000e+11
57,Europa,Dänemark,5336394.0,1.277000e+11
66,Europa,Estland,1431471.0,7.900000e+09
69,Europa,Faroe Islands,45296.0,7.000000e+08
71,Europa,Finnland,5167486.0,1.086000e+11
72,Europa,Frankreich,59329691.0,1.373000e+12
78,Osteuropa,Georgia,5019538.0,1.170000e+10
79,Europa,Deutschland,82797408.0,1.864000e+12
81,Europa,Gibraltar,29481.0,NaN
82,Europa,Griechenland,10601527.0,1.492000e+11
88,Europa,Guernsey,64080.0,1.150000e+09
93,Europa,Vatikan Stadt,880.0,NaN
96,Europa,Ungarn,10138844.0,7.940000e+10
102,Europa,Irland,3797257.0,7.370000e+10
104,Europa,Italien,57634327.0,1.212000e+12
107,Europa,Jersey,88915.0,2.200000e+09
109,Osteuropa,Kasachstan,16733227.0,5.450000e+10
115,Osteuropa,Kyrgyzstan,4685230.0,1.030000e+10
117,Europa,Latvia,2404926.0,9.800000e+09
122,Europa,Liechtenstein,32207.0,7.300000e+08
123,Europa,Litauen,3620756.0,1.730000e+10
124,Europa,Luxemburg,437389.0,1.470000e+10
126,Europa,Macedonia The Former Yugoslav Republic of,2041467.0,7.600000e+09
132,Europa,Malta,391670.0,5.000000e+00
133,Europa,Man Isle of,73117.0,1.200000e+09
141,Osteuropa,Moldova,4430654.0,9.700000e+09
142,Europa,Monaco,31693.0,8.700000e+08
150,Europa,Niederlande,15892237.0,3.651000e+11
160,Europa,Norwegen,4481162.0,1.113000e+11
170,Europa,Polen,38646023.0,2.765000e+11
171,Europa,Portugal,10048232.0,1.514000e+11
174,Europa,Rum„nien,22411121.0,8.740000e+10
183,Europa,San Marino,26937.0,5.000000e+08
187,Europa,Serbien und Montenegro,10662087.0,2.060000e+10
191,Europa,Slowakei,5407956.0,4.590000e+10
192,Europa,Slowenien,1927593.0,2.140000e+10
196,Europa,Spanien,39996671.0,6.775000e+11
202,Europa,Schweden,8873052.0,1.840000e+11
203,Europa,Schweiz,7262372.0,1.970000e+11
206,Osteuropa,Tajikistan,6440732.0,6.200000e+09
214,Europa,Türkei,65666677.0,4.094000e+11
215,Osteuropa,Turkmenistan,4518268.0,7.700000e+09
219,Osteuropa,Ukraine,49153027.0,1.095000e+11
221,Europa,Groß-Britannien,59511464.0,1.290000e+12
224,Osteuropa,Uzbekistan,24755519.0,5.930000e+10

Aufgabe 5
Ermittle die Flächen des kleinsten und größten Landes.

In [23]:
df.columns

Index(['LID', 'Name', 'Region', 'Flaeche', 'Einwohner', 'BIP'], dtype='object')

In [46]:
df["Flaeche"].min()

0

In [47]:
df["Flaeche"].max()

17075200

In [44]:
df[ ( df["Flaeche"] == df["Flaeche"].min() ) | ( df["Flaeche"] == df["Flaeche"].max() ) ]

     LID           Name  Region   Flaeche    Einwohner           BIP
93    94  Vatikan Stadt  Europa         0        880.0           NaN
175  176       Russland   Asien  17075200  146001176.0  6.203000e+11

Aufgabe 6
Wie viele Regionen gibt es?

In [6]:
pd.DataFrame(pd.unique( df["Region"] )).count()

0    13
dtype: int64