# CIA-Datenbank mit Python bearbeiten
### Ziel: SQL-Tutorial-Aufgaben mit Jupiter-Notebook, SQLite und Pandas lösen 

## Proof of Concept - Matthias Ebert, DuP 2022

In [2]:
import sqlite3
con = sqlite3.connect("cia.db")   # verbindet mit eine SQLite3-Datei als Datenbank (legt sie bei Bedarf neu an)
                                  # enspricht in SQL:  CREATE DATABASE `cia_db`; und USE `cia_db` 
#con = sqlite3.connect(":memory:")   # Tabellen existieren hier nur zur Laufzeit im Memory

In [3]:
# Muss man nur Ausführen, wenn :memory: gewählt oder cia.db neu angelegt werden soll
con.executescript("""
--
-- Tabellenstruktur für Tabelle `cia`
--
DROP TABLE IF EXISTS `cia`;

CREATE TABLE `cia` (
  `LID` INTEGER PRIMARY KEY AUTOINCREMENT,
  `Name` varchar(80) NOT NULL,
  `Region` varchar(80) NOT NULL,
  `Flaeche` bigint,
  `Einwohner` bigint,
  `BIP` bigint
);

--
-- Daten für Tabelle `cia`
--

INSERT INTO `cia` (`Name`, `Region`, `Flaeche`, `Einwohner`, `BIP`) VALUES
("Afghanistan","Asien",652000,25838797,21000000000),
("Albanien","Europa",28748,3490435,5600000000),
("Algerien","Afrika",2381740,31193917,147600000000),
("Amerikanische Samoa-Inseln","Ozeanien",199,65446,150000000),
("Andorra","Europa",468,66824,1200000000),
("Angola","Afrika",1246700,10145267,11600000000),
("Anguilla","Mittelamerika",91,11797,88000000),
("Antarktik","Antarktis",14000000,NULL,NULL),
("Antigua und Barbuda","Mittelamerika",442,66422,524000000),
("Argentinien","Südamerika",2766890,36955182,367000000000),
("Armenien","Osteuropa",29800,3344336,9900000000),
("Aruba","Mittelamerika",193,69539,1600000000),
("Australien","Ozeanien",7686850,19169083,416200000000),
("Österreich","Europa",83858,8131111,190600000000),
("Azerbaijan","Osteuropa",86600,7748163,14000000000),
("Bahamas","Mittelamerika",13940,294982,5580000000),
("Bahrain","Mittlerer Osten",620,634137,8600000000),
("Bangladesh","Asien",144000,129194224,187000000000),
("Barbados","Mittelamerika",430,274540,2900000000),
("Belarus","Osteuropa",207600,10366719,55200000000),
("Belgien","Europa",30510,10241506,243400000000),
("Belize","Mittelamerika",22960,249183,740000000),
("Benin","Afrika",112620,6395919,8100000000),
("Bermuda","Nordamerika",58,62997,2000000000),
("Bhutan","Asien",47000,2005222,2100000000),
("Bolivien","Südamerika",1098580,8152620,24200000000),
("Bosnien und Herzegovina","Europa",51129,3835777,6200000000),
("Botswana","Afrika",600370,1576470,5700000000),
("Brasilien","Südamerika",8511965,172860370,1130000000000),
("British Virgin Islands","Mittelamerika",150,19615,287000000),
("Brunei","Südostasien",5770,336376,5600000000),
("Bulgarien","Europa",110910,7796694,34900000000),
("Burkina Faso","Afrika",274200,11946065,12400000000),
("Burma","Südostasien",678500,41734853,59400000000),
("Burundi","Afrika",27830,6054714,4200000000),
("Kambodscha","Südostasien",181040,12212306,8200000000),
("Cameroon","Afrika",475440,15421937,31500000000),
("Kanada","Nordamerika",9976140,31281092,722300000000),
("Cape Verde","Welt",4033,401343,618000000),
("Cayman-Inseln","Afrika",259,34763,930000000),
("Zentral-Afrikanische Republik","Afrika",622984,3512751,5800000000),
("Tschad","Afrika",1284000,8424504,7600000000),
("Chile","Südamerika",756950,15153797,185100000000),
("China","Asien",9596960,1261832482,4800000000000),
("Christmas Island","Südostasien",135,2564,NULL),
("Cocos )(Keeling) Islands","Südostasien",14,635,NULL),
("Kolumbien","Südamerika",1138910,39685655,245100000000),
("Comoren","Afrika",2170,578400,410000000),
("Kongo demokratische Republik","Afrika",2345410,51964999,35700000000),
("Kongo demokratische Republik","Afrika",342000,2830961,4150000000),
("Cook Islands","Ozeanien",240,20407,112000000),
("Costa-Rica","Mittelamerika",51100,3710558,26000000000),
("Cote d Ivoire","Afrika",322460,15980950,25700000000),
("Kroatien","Europa",56538,4282216,23900000000),
("Kuba","Mittelamerika",110860,11141997,18600000000),
("Zypern","Mittlerer Osten",9250,758363,9000000),
("Tschechische Republik","Europa",78866,10272179,120800000000),
("Dänemark","Europa",43094,5336394,127700000000),
("Djibouti","Afrika",22000,451442,550000000),
("Dominica","Mittelamerika",754,71540,225000000),
("Dominikanische Republik","Mittelamerika",48730,8442533,43700000000),
("Ecuador","Südamerika",283560,12920092,54500000000),
("Ägypten","Afrika",1001450,68359979,200000000000),
("El Salvador","Mittelamerika",21040,6122515,18100000000),
("Äquatoriale Guine","Afrika",28051,474214,960000000),
("Eritrea","Afrika",121320,4135933,2900000000),
("Estland","Europa",45226,1431471,7900000000),
("Äthiopien","Afrika",1127127,64117452,33300000000),
("Falkland Islands (Islas Malvinas)","Südamerika",12173,2826,NULL),
("Faroe Islands","Europa",1399,45296,700000000),
("Fidschi","Ozeanien",18270,832494,5900000000),
("Finnland","Europa",337030,5167486,108600000000),
("Frankreich","Europa",547030,59329691,1373000000000),
("Französisch-Guayana","Südamerika",91000,172605,1000000000),
("Französisch-Polynesien","Ozeanien",4167,249110,2600000000),
("Gabun","Afrika",267667,1208436,7900000000),
("Gambia","Afrika",11300,1367124,1400000000),
("Gazastreifen","Mittlerer Osten",360,1132063,1170000000),
("Georgia","Osteuropa",69700,5019538,11700000000),
("Deutschland","Europa",357021,82797408,1864000000000),
("Ghana","Afrika",238540,19533560,35500000000),
("Gibraltar","Europa",6,29481,NULL),
("Griechenland","Europa",131940,10601527,149200000000),
("Greenland","Arktik-Region",2175600,56309,945000000),
("Grenada","Mittelamerika",340,89018,360000000),
("Guadeloupe","Mittelamerika",1780,426493,3700000000),
("Guam","Ozeanien",541,154623,3000000000),
("Guatemala","Mittelamerika",108890,12639939,47900000000),
("Guernsey","Europa",194,64080,1150000000),
("Guine","Afrika",245857,7466200,9200000000),
("Guinea-Bissau","Afrika",36120,1285715,1100000000),
("Guyana","Südamerika",214970,697286,1860000000),
("Haiti","Mittelamerika",27750,6867995,9200000000),
("Vatikan Stadt","Europa",0,880,NULL),
("Honduras","Mittelamerika",112090,6249598,14100000000),
("Hong Kong","Südostasien",1092,7116302,158200000000),
("Ungarn","Europa",93030,10138844,79400000000),
("Island","Arktik-Region",103000,276365,6420000000),
("Indien","Asien",3287590,1014003817,1805000000000),
("Indonesien","Südostasien",1919440,224784210,610000000000),
("Iran","Mittlerer Osten",1648000,65619636,347600000000),
("Irak","Mittlerer Osten",437072,22675617,59900000000),
("Irland","Europa",70280,3797257,73700000000),
("Israel","Mittlerer Osten",20770,5842454,105400000000),
("Italien","Europa",301230,57634327,1212000000000),
("Jamaica","Mittelamerika",10990,2652689,8800000000),
("Japan","Asien",377835,126549976,2950000000000),
("Jersey","Europa",116,88915,2200000000),
("Jordanien","Mittlerer Osten",89213,4998564,16000000000),
("Kasachstan","Osteuropa",2717300,16733227,54500000000),
("Kenia","Afrika",582650,30339770,45100000000),
("Kiribati","Ozeanien",717,91985,74000000),
("Korea, Nord","Asien",120540,21687550,22600000000),
("Korea, Süd","Asien",98480,47470969,625700000000),
("Kuwait","Mittlerer Osten",17820,1973572,44800000000),
("Kyrgyzstan","Osteuropa",198500,4685230,10300000000),
("Laos","Südostasien",236800,5497459,7000000000),
("Latvia","Europa",64589,2404926,9800000000),
("Libanon","Mittlerer Osten",10400,3578036,16200000000),
("Lesotho","Afrika",30355,2143141,4700000000),
("Liberia","Afrika",111370,3164156,2850000000),
("Libya","Afrika",1759540,5115450,39300000000),
("Liechtenstein","Europa",160,32207,730000000),
("Litauen","Europa",65200,3620756,17300000000),
("Luxemburg","Europa",2586,437389,14700000000),
("Macau","Südostasien",21,445594,7650000000),
("Macedonia The Former Yugoslav Republic of","Europa",25333,2041467,7600000000),
("Madagascar","Afrika",587040,15506472,11500000000),
("Malawi","Afrika",118480,10385849,9400000000),
("Malaysia","Südostasien",329750,21793293,229100000000),
("Maldives","Asien",300,301475,540000000),
("Mali","Afrika",1240000,10685948,8500000000),
("Malta","Europa",316,391670,5),
("Man Isle of","Europa",572,73117,1200000000),
("Marshall Inseln","Ozeanien",181,68126,105000000),
("Martinique","Mittelamerika",1100,414516,4240000000),
("Mauritania","Afrika",1030700,2667859,4900000000),
("Mauritius","Welt",1860,1179368,12300000000),
("Mayotte","Afrika",374,155911,85000000),
("Mexiko","Nordamerika",1972550,100349766,865500000000),
("Micronesia, Federated States of","Ozeanien",702,133144,240000000),
("Moldova","Osteuropa",33843,4430654,9700000000),
("Monaco","Europa",1,31693,870000000),
("Mongolei","Asien",1565000,2650952,6100000000),
("Montserrat","Mittelamerika",100,6409,31000000),
("Marocco","Afrika",446550,30122350,108000000000),
("Mozambique","Afrika",801590,19104696,18700000000),
("Namibia","Afrika",825418,1771327,7100000000),
("Nauru","Ozeanien",21,11845,100000000),
("Nepal","Asien",140800,24702119,27400000000),
("Niederlande","Europa",41532,15892237,365100000000),
("Niederländische Antillen","Mittelamerika",960,210134,2400000000),
("New Caledonia","Ozeanien",19060,201816,3000000000),
("Neuseeland","Ozeanien",268680,3819762,63800000000),
("Nicaragua","Mittelamerika",129494,4812569,12500000000),
("Niger","Afrika",1267000,10075511,9600000000),
("Nigeria","Afrika",923768,123337822,110500000000),
("Niue","Ozeanien",260,2113,4500000),
("Norfolk Island","Ozeanien",34,1892,NULL),
("Northern Mariana Islands","Ozeanien",477,71912,524000000),
("Norwegen","Europa",324220,4481162,111300000000),
("Oman","Mittlerer Osten",212460,2533389,19600000000),
("Pakistan","Asien",803940,141553775,282000000000),
("Palau","Ozeanien",458,18766,160000000),
("Panama","Mittelamerika",78200,2808268,21000000000),
("Papua Neu Guinea","Ozeanien",462840,4926984,11600000000),
("Paraguay","Südamerika",406750,5585828,19900000000),
("Peru","Südamerika",1280000,27012899,116000000000),
("Philippinen","Südostasien",300000,81159644,282000000000),
("Pitcairn Islands","Ozeanien",47,54,NULL),
("Polen","Europa",312685,38646023,276500000000),
("Portugal","Europa",92391,10048232,151400000000),
("Puerto Rico","Mittelamerika",9104,3915798,38100000000),
("Qatar","Mittlerer Osten",11437,744483,12300000000),
("Rum„nien","Europa",237500,22411121,87400000000),
("Russland","Asien",17075200,146001176,620300000000),
("Rwanda","Afrika",26338,7229129,5900000000),
("Saint Helena","Afrika",410,7212,13900000),
("Saint Kitts und Nevis","Mittelamerika",261,38819,244000000),
("Saint Lucia","Mittelamerika",620,156260,656000000),
("Saint Pierre und Miquelon","Nordamerika",242,6896,74000000),
("Saint Vincent und die Grenadines","Mittelamerika",389,115461,309000000),
("Samoa","Ozeanien",2860,179466,485000000),
("San Marino","Europa",60,26937,500000000),
("Sao Tome und Principe","Afrika",1001,159883,169000000),
("Saudi-Arabien","Mittlerer Osten",1960582,22023506,191000000000),
("Senegal","Afrika",196190,9987494,16600000000),
("Serbien und Montenegro","Europa",102350,10662087,20600000000),
("Seychellen","Afrika",455,79326,590000000),
("Sierra Leone","Afrika",71740,5232624,2500000000),
("Singapur","Südostasien",647,4151264,98000000000),
("Slowakei","Europa",48845,5407956,45900000000),
("Slowenien","Europa",20253,1927593,21400000000),
("Solomon Islands","Ozeanien",28450,466194,1210000000),
("Somalia","Afrika",637657,7253137,4300000000),
("SüdAfrika","Afrika",1219912,43421021,296100000000),
("Spanien","Europa",504782,39996671,677500000000),
("Sri Lanka","Asien",65610,19238575,50500000000),
("Sudan","Afrika",2505810,35079814,32600000000),
("Suriname","Südamerika",163270,431303,1480000000),
("Svalbard","Arktik-Region",62049,2416,NULL),
("Swaziland","Afrika",17363,1083289,4200000000),
("Schweden","Europa",449964,8873052,184000000000),
("Schweiz","Europa",41290,7262372,197000000000),
("Syrien","Mittlerer Osten",185180,16305659,42200000000),
("Taiwan","Südostasien",35980,22191087,357000000000),
("Tajikistan","Osteuropa",143100,6440732,6200000000),
("Tanzania","Afrika",945087,35306126,23300000000),
("Thailand","Südostasien",514000,61230874,388700000000),
("Togo","Afrika",56785,5018502,8600000000),
("Tokelau","Ozeanien",10,1458,1500000),
("Tonga","Ozeanien",748,102321,238000000),
("Trinidad und Tobago","Mittelamerika",5128,1175523,9410000000),
("Tunesien","Mittlerer Osten",163610,9593402,52600000000),
("Türkei","Europa",780580,65666677,409400000000),
("Turkmenistan","Osteuropa",488100,4518268,7700000000),
("Turks and Caicos Inseln","Mittelamerika",430,17502,117000000),
("Tuvalu","Ozeanien",26,10838,7800000),
("Uganda","Afrika",236040,23317560,24200000000),
("Ukraine","Osteuropa",603700,49153027,109500000000),
("Vereinigte Arabische Emirate","Mittlerer Osten",82880,2369153,41500000000),
("Groß-Britannien","Europa",244820,59511464,1290000000000),
("Vereinigte Staaten von Amerika","Nordamerika",9629091,275562673,9255000000000),
("Uruguay","Südamerika",176220,3334074,28000000000),
("Uzbekistan","Osteuropa",447400,24755519,59300000000),
("Vanuatu","Ozeanien",14760,189618,245000000),
("Venezuela","Südamerika",912050,23542649,182800000000),
("Vietnam","Südostasien",329560,78773873,143100000000),
("Virgin Islands","Mittelamerika",352,120917,1800000000),
("Wallis und Futuna","Ozeanien",274,15283,28700000),
("West Bank","Mittlerer Osten",5860,2020298,3300000000),
("Westliche Sahara","Afrika",266000,244943,NULL),
("Jemen","Mittlerer Osten",527970,17479206,12700000000),
("Zambia","Afrika",752614,9582418,8500000000),
("Zimbabwe","Afrika",390580,11342521,26500000000);

""")

In [4]:
result = con.execute("SELECT * FROM cia").fetchall()
result

[(1, 'Afghanistan', 'Asien', 652000, 25838797, 21000000000),
 (2, 'Albanien', 'Europa', 28748, 3490435, 5600000000),
 (3, 'Algerien', 'Afrika', 2381740, 31193917, 147600000000),
 (4, 'Amerikanische Samoa-Inseln', 'Ozeanien', 199, 65446, 150000000),
 (5, 'Andorra', 'Europa', 468, 66824, 1200000000),
 (6, 'Angola', 'Afrika', 1246700, 10145267, 11600000000),
 (7, 'Anguilla', 'Mittelamerika', 91, 11797, 88000000),
 (8, 'Antarktik', 'Antarktis', 14000000, None, None),
 (9, 'Antigua und Barbuda', 'Mittelamerika', 442, 66422, 524000000),
 (10, 'Argentinien', 'Südamerika', 2766890, 36955182, 367000000000),
 (11, 'Armenien', 'Osteuropa', 29800, 3344336, 9900000000),
 (12, 'Aruba', 'Mittelamerika', 193, 69539, 1600000000),
 (13, 'Australien', 'Ozeanien', 7686850, 19169083, 416200000000),
 (14, 'Österreich', 'Europa', 83858, 8131111, 190600000000),
 (15, 'Azerbaijan', 'Osteuropa', 86600, 7748163, 14000000000),
 (16, 'Bahamas', 'Mittelamerika', 13940, 294982, 5580000000),
 (17, 'Bahrain', 'Mittlerer Osten', 620, 634137, 8600000000),
 (18, 'Bangladesh', 'Asien', 144000, 129194224, 187000000000),
 (19, 'Barbados', 'Mittelamerika', 430, 274540, 2900000000),
 (20, 'Belarus', 'Osteuropa', 207600, 10366719, 55200000000),
 (21, 'Belgien', 'Europa', 30510, 10241506, 243400000000),
 (22, 'Belize', 'Mittelamerika', 22960, 249183, 740000000),
 (23, 'Benin', 'Afrika', 112620, 6395919, 8100000000),
 (24, 'Bermuda', 'Nordamerika', 58, 62997, 2000000000),
 (25, 'Bhutan', 'Asien', 47000, 2005222, 2100000000),
 (26, 'Bolivien', 'Südamerika', 1098580, 8152620, 24200000000),
 (27, 'Bosnien und Herzegovina', 'Europa', 51129, 3835777, 6200000000),
 (28, 'Botswana', 'Afrika', 600370, 1576470, 5700000000),
 (29, 'Brasilien', 'Südamerika', 8511965, 172860370, 1130000000000),
 (30, 'British Virgin Islands', 'Mittelamerika', 150, 19615, 287000000),
 (31, 'Brunei', 'Südostasien', 5770, 336376, 5600000000),
 (32, 'Bulgarien', 'Europa', 110910, 7796694, 34900000000),
 (33, 'Burkina Faso', 'Afrika', 274200, 11946065, 12400000000),
 (34, 'Burma', 'Südostasien', 678500, 41734853, 59400000000),
 (35, 'Burundi', 'Afrika', 27830, 6054714, 4200000000),
 (36, 'Kambodscha', 'Südostasien', 181040, 12212306, 8200000000),
 (37, 'Cameroon', 'Afrika', 475440, 15421937, 31500000000),
 (38, 'Kanada', 'Nordamerika', 9976140, 31281092, 722300000000),
 (39, 'Cape Verde', 'Welt', 4033, 401343, 618000000),
 (40, 'Cayman-Inseln', 'Afrika', 259, 34763, 930000000),
 (41, 'Zentral-Afrikanische Republik', 'Afrika', 622984, 3512751, 5800000000),
 (42, 'Tschad', 'Afrika', 1284000, 8424504, 7600000000),
 (43, 'Chile', 'Südamerika', 756950, 15153797, 185100000000),
 (44, 'China', 'Asien', 9596960, 1261832482, 4800000000000),
 (45, 'Christmas Island', 'Südostasien', 135, 2564, None),
 (46, 'Cocos )(Keeling) Islands', 'Südostasien', 14, 635, None),
 (47, 'Kolumbien', 'Südamerika', 1138910, 39685655, 245100000000),
 (48, 'Comoren', 'Afrika', 2170, 578400, 410000000),
 (49,
  'Kongo demokratische Republik',
  'Afrika',
  2345410,
  51964999,
  35700000000),
 (50, 'Kongo demokratische Republik', 'Afrika', 342000, 2830961, 4150000000),
 (51, 'Cook Islands', 'Ozeanien', 240, 20407, 112000000),
 (52, 'Costa-Rica', 'Mittelamerika', 51100, 3710558, 26000000000),
 (53, 'Cote d Ivoire', 'Afrika', 322460, 15980950, 25700000000),
 (54, 'Kroatien', 'Europa', 56538, 4282216, 23900000000),
 (55, 'Kuba', 'Mittelamerika', 110860, 11141997, 18600000000),
 (56, 'Zypern', 'Mittlerer Osten', 9250, 758363, 9000000),
 (57, 'Tschechische Republik', 'Europa', 78866, 10272179, 120800000000),
 (58, 'Dänemark', 'Europa', 43094, 5336394, 127700000000),
 (59, 'Djibouti', 'Afrika', 22000, 451442, 550000000),
 (60, 'Dominica', 'Mittelamerika', 754, 71540, 225000000),
 (61, 'Dominikanische Republik', 'Mittelamerika', 48730, 8442533, 43700000000),
 (62, 'Ecuador', 'Südamerika', 283560, 12920092, 54500000000),
 (63, 'Ägypten', 'Afrika', 1001450, 68359979, 200000000000),
 (64, 'El Salvador', 'Mittelamerika', 21040, 6122515, 18100000000),
 (65, 'Äquatoriale Guine', 'Afrika', 28051, 474214, 960000000),
 (66, 'Eritrea', 'Afrika', 121320, 4135933, 2900000000),
 (67, 'Estland', 'Europa', 45226, 1431471, 7900000000),
 (68, 'Äthiopien', 'Afrika', 1127127, 64117452, 33300000000),
 (69, 'Falkland Islands (Islas Malvinas)', 'Südamerika', 12173, 2826, None),
 (70, 'Faroe Islands', 'Europa', 1399, 45296, 700000000),
 (71, 'Fidschi', 'Ozeanien', 18270, 832494, 5900000000),
 (72, 'Finnland', 'Europa', 337030, 5167486, 108600000000),
 (73, 'Frankreich', 'Europa', 547030, 59329691, 1373000000000),
 (74, 'Französisch-Guayana', 'Südamerika', 91000, 172605, 1000000000),
 (75, 'Französisch-Polynesien', 'Ozeanien', 4167, 249110, 2600000000),
 (76, 'Gabun', 'Afrika', 267667, 1208436, 7900000000),
 (77, 'Gambia', 'Afrika', 11300, 1367124, 1400000000),
 (78, 'Gazastreifen', 'Mittlerer Osten', 360, 1132063, 1170000000),
 (79, 'Georgia', 'Osteuropa', 69700, 5019538, 11700000000),
 (80, 'Deutschland', 'Europa', 357021, 82797408, 1864000000000),
 (81, 'Ghana', 'Afrika', 238540, 19533560, 35500000000),
 (82, 'Gibraltar', 'Europa', 6, 29481, None),
 (83, 'Griechenland', 'Europa', 131940, 10601527, 149200000000),
 (84, 'Greenland', 'Arktik-Region', 2175600, 56309, 945000000),
 (85, 'Grenada', 'Mittelamerika', 340, 89018, 360000000),
 (86, 'Guadeloupe', 'Mittelamerika', 1780, 426493, 3700000000),
 (87, 'Guam', 'Ozeanien', 541, 154623, 3000000000),
 (88, 'Guatemala', 'Mittelamerika', 108890, 12639939, 47900000000),
 (89, 'Guernsey', 'Europa', 194, 64080, 1150000000),
 (90, 'Guine', 'Afrika', 245857, 7466200, 9200000000),
 (91, 'Guinea-Bissau', 'Afrika', 36120, 1285715, 1100000000),
 (92, 'Guyana', 'Südamerika', 214970, 697286, 1860000000),
 (93, 'Haiti', 'Mittelamerika', 27750, 6867995, 9200000000),
 (94, 'Vatikan Stadt', 'Europa', 0, 880, None),
 (95, 'Honduras', 'Mittelamerika', 112090, 6249598, 14100000000),
 (96, 'Hong Kong', 'Südostasien', 1092, 7116302, 158200000000),
 (97, 'Ungarn', 'Europa', 93030, 10138844, 79400000000),
 (98, 'Island', 'Arktik-Region', 103000, 276365, 6420000000),
 (99, 'Indien', 'Asien', 3287590, 1014003817, 1805000000000),
 (100, 'Indonesien', 'Südostasien', 1919440, 224784210, 610000000000),
 (101, 'Iran', 'Mittlerer Osten', 1648000, 65619636, 347600000000),
 (102, 'Irak', 'Mittlerer Osten', 437072, 22675617, 59900000000),
 (103, 'Irland', 'Europa', 70280, 3797257, 73700000000),
 (104, 'Israel', 'Mittlerer Osten', 20770, 5842454, 105400000000),
 (105, 'Italien', 'Europa', 301230, 57634327, 1212000000000),
 (106, 'Jamaica', 'Mittelamerika', 10990, 2652689, 8800000000),
 (107, 'Japan', 'Asien', 377835, 126549976, 2950000000000),
 (108, 'Jersey', 'Europa', 116, 88915, 2200000000),
 (109, 'Jordanien', 'Mittlerer Osten', 89213, 4998564, 16000000000),
 (110, 'Kasachstan', 'Osteuropa', 2717300, 16733227, 54500000000),
 (111, 'Kenia', 'Afrika', 582650, 30339770, 45100000000),
 (112, 'Kiribati', 'Ozeanien', 717, 91985, 74000000),
 (113, 'Korea, Nord', 'Asien', 120540, 21687550, 22600000000),
 (114, 'Korea, Süd', 'Asien', 98480, 47470969, 625700000000),
 (115, 'Kuwait', 'Mittlerer Osten', 17820, 1973572, 44800000000),
 (116, 'Kyrgyzstan', 'Osteuropa', 198500, 4685230, 10300000000),
 (117, 'Laos', 'Südostasien', 236800, 5497459, 7000000000),
 (118, 'Latvia', 'Europa', 64589, 2404926, 9800000000),
 (119, 'Libanon', 'Mittlerer Osten', 10400, 3578036, 16200000000),
 (120, 'Lesotho', 'Afrika', 30355, 2143141, 4700000000),
 (121, 'Liberia', 'Afrika', 111370, 3164156, 2850000000),
 (122, 'Libya', 'Afrika', 1759540, 5115450, 39300000000),
 (123, 'Liechtenstein', 'Europa', 160, 32207, 730000000),
 (124, 'Litauen', 'Europa', 65200, 3620756, 17300000000),
 (125, 'Luxemburg', 'Europa', 2586, 437389, 14700000000),
 (126, 'Macau', 'Südostasien', 21, 445594, 7650000000),
 (127,
  'Macedonia The Former Yugoslav Republic of',
  'Europa',
  25333,
  2041467,
  7600000000),
 (128, 'Madagascar', 'Afrika', 587040, 15506472, 11500000000),
 (129, 'Malawi', 'Afrika', 118480, 10385849, 9400000000),
 (130, 'Malaysia', 'Südostasien', 329750, 21793293, 229100000000),
 (131, 'Maldives', 'Asien', 300, 301475, 540000000),
 (132, 'Mali', 'Afrika', 1240000, 10685948, 8500000000),
 (133, 'Malta', 'Europa', 316, 391670, 5),
 (134, 'Man Isle of', 'Europa', 572, 73117, 1200000000),
 (135, 'Marshall Inseln', 'Ozeanien', 181, 68126, 105000000),
 (136, 'Martinique', 'Mittelamerika', 1100, 414516, 4240000000),
 (137, 'Mauritania', 'Afrika', 1030700, 2667859, 4900000000),
 (138, 'Mauritius', 'Welt', 1860, 1179368, 12300000000),
 (139, 'Mayotte', 'Afrika', 374, 155911, 85000000),
 (140, 'Mexiko', 'Nordamerika', 1972550, 100349766, 865500000000),
 (141, 'Micronesia, Federated States of', 'Ozeanien', 702, 133144, 240000000),
 (142, 'Moldova', 'Osteuropa', 33843, 4430654, 9700000000),
 (143, 'Monaco', 'Europa', 1, 31693, 870000000),
 (144, 'Mongolei', 'Asien', 1565000, 2650952, 6100000000),
 (145, 'Montserrat', 'Mittelamerika', 100, 6409, 31000000),
 (146, 'Marocco', 'Afrika', 446550, 30122350, 108000000000),
 (147, 'Mozambique', 'Afrika', 801590, 19104696, 18700000000),
 (148, 'Namibia', 'Afrika', 825418, 1771327, 7100000000),
 (149, 'Nauru', 'Ozeanien', 21, 11845, 100000000),
 (150, 'Nepal', 'Asien', 140800, 24702119, 27400000000),
 (151, 'Niederlande', 'Europa', 41532, 15892237, 365100000000),
 (152, 'Niederländische Antillen', 'Mittelamerika', 960, 210134, 2400000000),
 (153, 'New Caledonia', 'Ozeanien', 19060, 201816, 3000000000),
 (154, 'Neuseeland', 'Ozeanien', 268680, 3819762, 63800000000),
 (155, 'Nicaragua', 'Mittelamerika', 129494, 4812569, 12500000000),
 (156, 'Niger', 'Afrika', 1267000, 10075511, 9600000000),
 (157, 'Nigeria', 'Afrika', 923768, 123337822, 110500000000),
 (158, 'Niue', 'Ozeanien', 260, 2113, 4500000),
 (159, 'Norfolk Island', 'Ozeanien', 34, 1892, None),
 (160, 'Northern Mariana Islands', 'Ozeanien', 477, 71912, 524000000),
 (161, 'Norwegen', 'Europa', 324220, 4481162, 111300000000),
 (162, 'Oman', 'Mittlerer Osten', 212460, 2533389, 19600000000),
 (163, 'Pakistan', 'Asien', 803940, 141553775, 282000000000),
 (164, 'Palau', 'Ozeanien', 458, 18766, 160000000),
 (165, 'Panama', 'Mittelamerika', 78200, 2808268, 21000000000),
 (166, 'Papua Neu Guinea', 'Ozeanien', 462840, 4926984, 11600000000),
 (167, 'Paraguay', 'Südamerika', 406750, 5585828, 19900000000),
 (168, 'Peru', 'Südamerika', 1280000, 27012899, 116000000000),
 (169, 'Philippinen', 'Südostasien', 300000, 81159644, 282000000000),
 (170, 'Pitcairn Islands', 'Ozeanien', 47, 54, None),
 (171, 'Polen', 'Europa', 312685, 38646023, 276500000000),
 (172, 'Portugal', 'Europa', 92391, 10048232, 151400000000),
 (173, 'Puerto Rico', 'Mittelamerika', 9104, 3915798, 38100000000),
 (174, 'Qatar', 'Mittlerer Osten', 11437, 744483, 12300000000),
 (175, 'Rum„nien', 'Europa', 237500, 22411121, 87400000000),
 (176, 'Russland', 'Asien', 17075200, 146001176, 620300000000),
 (177, 'Rwanda', 'Afrika', 26338, 7229129, 5900000000),
 (178, 'Saint Helena', 'Afrika', 410, 7212, 13900000),
 (179, 'Saint Kitts und Nevis', 'Mittelamerika', 261, 38819, 244000000),
 (180, 'Saint Lucia', 'Mittelamerika', 620, 156260, 656000000),
 (181, 'Saint Pierre und Miquelon', 'Nordamerika', 242, 6896, 74000000),
 (182,
  'Saint Vincent und die Grenadines',
  'Mittelamerika',
  389,
  115461,
  309000000),
 (183, 'Samoa', 'Ozeanien', 2860, 179466, 485000000),
 (184, 'San Marino', 'Europa', 60, 26937, 500000000),
 (185, 'Sao Tome und Principe', 'Afrika', 1001, 159883, 169000000),
 (186, 'Saudi-Arabien', 'Mittlerer Osten', 1960582, 22023506, 191000000000),
 (187, 'Senegal', 'Afrika', 196190, 9987494, 16600000000),
 (188, 'Serbien und Montenegro', 'Europa', 102350, 10662087, 20600000000),
 (189, 'Seychellen', 'Afrika', 455, 79326, 590000000),
 (190, 'Sierra Leone', 'Afrika', 71740, 5232624, 2500000000),
 (191, 'Singapur', 'Südostasien', 647, 4151264, 98000000000),
 (192, 'Slowakei', 'Europa', 48845, 5407956, 45900000000),
 (193, 'Slowenien', 'Europa', 20253, 1927593, 21400000000),
 (194, 'Solomon Islands', 'Ozeanien', 28450, 466194, 1210000000),
 (195, 'Somalia', 'Afrika', 637657, 7253137, 4300000000),
 (196, 'SüdAfrika', 'Afrika', 1219912, 43421021, 296100000000),
 (197, 'Spanien', 'Europa', 504782, 39996671, 677500000000),
 (198, 'Sri Lanka', 'Asien', 65610, 19238575, 50500000000),
 (199, 'Sudan', 'Afrika', 2505810, 35079814, 32600000000),
 (200, 'Suriname', 'Südamerika', 163270, 431303, 1480000000),
 (201, 'Svalbard', 'Arktik-Region', 62049, 2416, None),
 (202, 'Swaziland', 'Afrika', 17363, 1083289, 4200000000),
 (203, 'Schweden', 'Europa', 449964, 8873052, 184000000000),
 (204, 'Schweiz', 'Europa', 41290, 7262372, 197000000000),
 (205, 'Syrien', 'Mittlerer Osten', 185180, 16305659, 42200000000),
 (206, 'Taiwan', 'Südostasien', 35980, 22191087, 357000000000),
 (207, 'Tajikistan', 'Osteuropa', 143100, 6440732, 6200000000),
 (208, 'Tanzania', 'Afrika', 945087, 35306126, 23300000000),
 (209, 'Thailand', 'Südostasien', 514000, 61230874, 388700000000),
 (210, 'Togo', 'Afrika', 56785, 5018502, 8600000000),
 (211, 'Tokelau', 'Ozeanien', 10, 1458, 1500000),
 (212, 'Tonga', 'Ozeanien', 748, 102321, 238000000),
 (213, 'Trinidad und Tobago', 'Mittelamerika', 5128, 1175523, 9410000000),
 (214, 'Tunesien', 'Mittlerer Osten', 163610, 9593402, 52600000000),
 (215, 'Türkei', 'Europa', 780580, 65666677, 409400000000),
 (216, 'Turkmenistan', 'Osteuropa', 488100, 4518268, 7700000000),
 (217, 'Turks and Caicos Inseln', 'Mittelamerika', 430, 17502, 117000000),
 (218, 'Tuvalu', 'Ozeanien', 26, 10838, 7800000),
 (219, 'Uganda', 'Afrika', 236040, 23317560, 24200000000),
 (220, 'Ukraine', 'Osteuropa', 603700, 49153027, 109500000000),
 (221,
  'Vereinigte Arabische Emirate',
  'Mittlerer Osten',
  82880,
  2369153,
  41500000000),
 (222, 'Groß-Britannien', 'Europa', 244820, 59511464, 1290000000000),
 (223,
  'Vereinigte Staaten von Amerika',
  'Nordamerika',
  9629091,
  275562673,
  9255000000000),
 (224, 'Uruguay', 'Südamerika', 176220, 3334074, 28000000000),
 (225, 'Uzbekistan', 'Osteuropa', 447400, 24755519, 59300000000),
 (226, 'Vanuatu', 'Ozeanien', 14760, 189618, 245000000),
 (227, 'Venezuela', 'Südamerika', 912050, 23542649, 182800000000),
 (228, 'Vietnam', 'Südostasien', 329560, 78773873, 143100000000),
 (229, 'Virgin Islands', 'Mittelamerika', 352, 120917, 1800000000),
 (230, 'Wallis und Futuna', 'Ozeanien', 274, 15283, 28700000),
 (231, 'West Bank', 'Mittlerer Osten', 5860, 2020298, 3300000000),
 (232, 'Westliche Sahara', 'Afrika', 266000, 244943, None),
 (233, 'Jemen', 'Mittlerer Osten', 527970, 17479206, 12700000000),
 (234, 'Zambia', 'Afrika', 752614, 9582418, 8500000000),
 (235, 'Zimbabwe', 'Afrika', 390580, 11342521, 26500000000)]

## Zugriff auf einzelne Elemente ohne Pandas
mit Python: list of sets

In [5]:
len(result)

235

In [6]:
# Erste Zeile
print(result[0])

(1, 'Afghanistan', 'Asien', 652000, 25838797, 21000000000)

In [7]:
# Erste Spalte
for row in result:
    print(row[1])

Afghanistan
Albanien
Algerien
Amerikanische Samoa-Inseln
Andorra
Angola
Anguilla
Antarktik
Antigua und Barbuda
Argentinien
Armenien
Aruba
Australien
Österreich
Azerbaijan
Bahamas
Bahrain
Bangladesh
Barbados
Belarus
Belgien
Belize
Benin
Bermuda
Bhutan
Bolivien
Bosnien und Herzegovina
Botswana
Brasilien
British Virgin Islands
Brunei
Bulgarien
Burkina Faso
Burma
Burundi
Kambodscha
Cameroon
Kanada
Cape Verde
Cayman-Inseln
Zentral-Afrikanische Republik
Tschad
Chile
China
Christmas Island
Cocos )(Keeling) Islands
Kolumbien
Comoren
Kongo demokratische Republik
Kongo demokratische Republik
Cook Islands
Costa-Rica
Cote d Ivoire
Kroatien
Kuba
Zypern
Tschechische Republik
Dänemark
Djibouti
Dominica
Dominikanische Republik
Ecuador
Ägypten
El Salvador
Äquatoriale Guine
Eritrea
Estland
Äthiopien
Falkland Islands (Islas Malvinas)
Faroe Islands
Fidschi
Finnland
Frankreich
Französisch-Guayana
Französisch-Polynesien
Gabun
Gambia
Gazastreifen
Georgia
Deutschland
Ghana
Gibraltar
Griechenland
Greenland
Grenada
Guadeloupe
Guam
Guatemala
Guernsey
Guine
Guinea-Bissau
Guyana
Haiti
Vatikan Stadt
Honduras
Hong Kong
Ungarn
Island
Indien
Indonesien
Iran
Irak
Irland
Israel
Italien
Jamaica
Japan
Jersey
Jordanien
Kasachstan
Kenia
Kiribati
Korea, Nord
Korea, Süd
Kuwait
Kyrgyzstan
Laos
Latvia
Libanon
Lesotho
Liberia
Libya
Liechtenstein
Litauen
Luxemburg
Macau
Macedonia The Former Yugoslav Republic of
Madagascar
Malawi
Malaysia
Maldives
Mali
Malta
Man Isle of
Marshall Inseln
Martinique
Mauritania
Mauritius
Mayotte
Mexiko
Micronesia, Federated States of
Moldova
Monaco
Mongolei
Montserrat
Marocco
Mozambique
Namibia
Nauru
Nepal
Niederlande
Niederländische Antillen
New Caledonia
Neuseeland
Nicaragua
Niger
Nigeria
Niue
Norfolk Island
Northern Mariana Islands
Norwegen
Oman
Pakistan
Palau
Panama
Papua Neu Guinea
Paraguay
Peru
Philippinen
Pitcairn Islands
Polen
Portugal
Puerto Rico
Qatar
Rum„nien
Russland
Rwanda
Saint Helena
Saint Kitts und Nevis
Saint Lucia
Saint Pierre und Miquelon
Saint Vincent und die Grenadines
Samoa
San Marino
Sao Tome und Principe
Saudi-Arabien
Senegal
Serbien und Montenegro
Seychellen
Sierra Leone
Singapur
Slowakei
Slowenien
Solomon Islands
Somalia
SüdAfrika
Spanien
Sri Lanka
Sudan
Suriname
Svalbard
Swaziland
Schweden
Schweiz
Syrien
Taiwan
Tajikistan
Tanzania
Thailand
Togo
Tokelau
Tonga
Trinidad und Tobago
Tunesien
Türkei
Turkmenistan
Turks and Caicos Inseln
Tuvalu
Uganda
Ukraine
Vereinigte Arabische Emirate
Groß-Britannien
Vereinigte Staaten von Amerika
Uruguay
Uzbekistan
Vanuatu
Venezuela
Vietnam
Virgin Islands
Wallis und Futuna
West Bank
Westliche Sahara
Jemen
Zambia
Zimbabwe

In [8]:
# Alle Zeilen und Spalten
for row in result:
    for col in row:
        print(col, end="\t|")
    print()

1	|Afghanistan	|Asien	|652000	|25838797	|21000000000	|
2	|Albanien	|Europa	|28748	|3490435	|5600000000	|
3	|Algerien	|Afrika	|2381740	|31193917	|147600000000	|
4	|Amerikanische Samoa-Inseln	|Ozeanien	|199	|65446	|150000000	|
5	|Andorra	|Europa	|468	|66824	|1200000000	|
6	|Angola	|Afrika	|1246700	|10145267	|11600000000	|
7	|Anguilla	|Mittelamerika	|91	|11797	|88000000	|
8	|Antarktik	|Antarktis	|14000000	|None	|None	|
9	|Antigua und Barbuda	|Mittelamerika	|442	|66422	|524000000	|
10	|Argentinien	|Südamerika	|2766890	|36955182	|367000000000	|
11	|Armenien	|Osteuropa	|29800	|3344336	|9900000000	|
12	|Aruba	|Mittelamerika	|193	|69539	|1600000000	|
13	|Australien	|Ozeanien	|7686850	|19169083	|416200000000	|
14	|Österreich	|Europa	|83858	|8131111	|190600000000	|
15	|Azerbaijan	|Osteuropa	|86600	|7748163	|14000000000	|
16	|Bahamas	|Mittelamerika	|13940	|294982	|5580000000	|
17	|Bahrain	|Mittlerer Osten	|620	|634137	|8600000000	|
18	|Bangladesh	|Asien	|144000	|129194224	|187000000000	|
19	|Barbados	|Mittelamerika	|430	|274540	|2900000000	|
20	|Belarus	|Osteuropa	|207600	|10366719	|55200000000	|
21	|Belgien	|Europa	|30510	|10241506	|243400000000	|
22	|Belize	|Mittelamerika	|22960	|249183	|740000000	|
23	|Benin	|Afrika	|112620	|6395919	|8100000000	|
24	|Bermuda	|Nordamerika	|58	|62997	|2000000000	|
25	|Bhutan	|Asien	|47000	|2005222	|2100000000	|
26	|Bolivien	|Südamerika	|1098580	|8152620	|24200000000	|
27	|Bosnien und Herzegovina	|Europa	|51129	|3835777	|6200000000	|
28	|Botswana	|Afrika	|600370	|1576470	|5700000000	|
29	|Brasilien	|Südamerika	|8511965	|172860370	|1130000000000	|
30	|British Virgin Islands	|Mittelamerika	|150	|19615	|287000000	|
31	|Brunei	|Südostasien	|5770	|336376	|5600000000	|
32	|Bulgarien	|Europa	|110910	|7796694	|34900000000	|
33	|Burkina Faso	|Afrika	|274200	|11946065	|12400000000	|
34	|Burma	|Südostasien	|678500	|41734853	|59400000000	|
35	|Burundi	|Afrika	|27830	|6054714	|4200000000	|
36	|Kambodscha	|Südostasien	|181040	|12212306	|8200000000	|
37	|Cameroon	|Afrika	|475440	|15421937	|31500000000	|
38	|Kanada	|Nordamerika	|9976140	|31281092	|722300000000	|
39	|Cape Verde	|Welt	|4033	|401343	|618000000	|
40	|Cayman-Inseln	|Afrika	|259	|34763	|930000000	|
41	|Zentral-Afrikanische Republik	|Afrika	|622984	|3512751	|5800000000	|
42	|Tschad	|Afrika	|1284000	|8424504	|7600000000	|
43	|Chile	|Südamerika	|756950	|15153797	|185100000000	|
44	|China	|Asien	|9596960	|1261832482	|4800000000000	|
45	|Christmas Island	|Südostasien	|135	|2564	|None	|
46	|Cocos )(Keeling) Islands	|Südostasien	|14	|635	|None	|
47	|Kolumbien	|Südamerika	|1138910	|39685655	|245100000000	|
48	|Comoren	|Afrika	|2170	|578400	|410000000	|
49	|Kongo demokratische Republik	|Afrika	|2345410	|51964999	|35700000000	|
50	|Kongo demokratische Republik	|Afrika	|342000	|2830961	|4150000000	|
51	|Cook Islands	|Ozeanien	|240	|20407	|112000000	|
52	|Costa-Rica	|Mittelamerika	|51100	|3710558	|26000000000	|
53	|Cote d Ivoire	|Afrika	|322460	|15980950	|25700000000	|
54	|Kroatien	|Europa	|56538	|4282216	|23900000000	|
55	|Kuba	|Mittelamerika	|110860	|11141997	|18600000000	|
56	|Zypern	|Mittlerer Osten	|9250	|758363	|9000000	|
57	|Tschechische Republik	|Europa	|78866	|10272179	|120800000000	|
58	|Dänemark	|Europa	|43094	|5336394	|127700000000	|
59	|Djibouti	|Afrika	|22000	|451442	|550000000	|
60	|Dominica	|Mittelamerika	|754	|71540	|225000000	|
61	|Dominikanische Republik	|Mittelamerika	|48730	|8442533	|43700000000	|
62	|Ecuador	|Südamerika	|283560	|12920092	|54500000000	|
63	|Ägypten	|Afrika	|1001450	|68359979	|200000000000	|
64	|El Salvador	|Mittelamerika	|21040	|6122515	|18100000000	|
65	|Äquatoriale Guine	|Afrika	|28051	|474214	|960000000	|
66	|Eritrea	|Afrika	|121320	|4135933	|2900000000	|
67	|Estland	|Europa	|45226	|1431471	|7900000000	|
68	|Äthiopien	|Afrika	|1127127	|64117452	|33300000000	|
69	|Falkland Islands (Islas Malvinas)	|Südamerika	|12173	|2826	|None	|
70	|Faroe Islands	|Europa	|1399	|45296	|700000000	|
71	|Fidschi	|Ozeanien	|18270	|832494	|5900000000	|
72	|Finnland	|Europa	|337030	|5167486	|108600000000	|
73	|Frankreich	|Europa	|547030	|59329691	|1373000000000	|
74	|Französisch-Guayana	|Südamerika	|91000	|172605	|1000000000	|
75	|Französisch-Polynesien	|Ozeanien	|4167	|249110	|2600000000	|
76	|Gabun	|Afrika	|267667	|1208436	|7900000000	|
77	|Gambia	|Afrika	|11300	|1367124	|1400000000	|
78	|Gazastreifen	|Mittlerer Osten	|360	|1132063	|1170000000	|
79	|Georgia	|Osteuropa	|69700	|5019538	|11700000000	|
80	|Deutschland	|Europa	|357021	|82797408	|1864000000000	|
81	|Ghana	|Afrika	|238540	|19533560	|35500000000	|
82	|Gibraltar	|Europa	|6	|29481	|None	|
83	|Griechenland	|Europa	|131940	|10601527	|149200000000	|
84	|Greenland	|Arktik-Region	|2175600	|56309	|945000000	|
85	|Grenada	|Mittelamerika	|340	|89018	|360000000	|
86	|Guadeloupe	|Mittelamerika	|1780	|426493	|3700000000	|
87	|Guam	|Ozeanien	|541	|154623	|3000000000	|
88	|Guatemala	|Mittelamerika	|108890	|12639939	|47900000000	|
89	|Guernsey	|Europa	|194	|64080	|1150000000	|
90	|Guine	|Afrika	|245857	|7466200	|9200000000	|
91	|Guinea-Bissau	|Afrika	|36120	|1285715	|1100000000	|
92	|Guyana	|Südamerika	|214970	|697286	|1860000000	|
93	|Haiti	|Mittelamerika	|27750	|6867995	|9200000000	|
94	|Vatikan Stadt	|Europa	|0	|880	|None	|
95	|Honduras	|Mittelamerika	|112090	|6249598	|14100000000	|
96	|Hong Kong	|Südostasien	|1092	|7116302	|158200000000	|
97	|Ungarn	|Europa	|93030	|10138844	|79400000000	|
98	|Island	|Arktik-Region	|103000	|276365	|6420000000	|
99	|Indien	|Asien	|3287590	|1014003817	|1805000000000	|
100	|Indonesien	|Südostasien	|1919440	|224784210	|610000000000	|
101	|Iran	|Mittlerer Osten	|1648000	|65619636	|347600000000	|
102	|Irak	|Mittlerer Osten	|437072	|22675617	|59900000000	|
103	|Irland	|Europa	|70280	|3797257	|73700000000	|
104	|Israel	|Mittlerer Osten	|20770	|5842454	|105400000000	|
105	|Italien	|Europa	|301230	|57634327	|1212000000000	|
106	|Jamaica	|Mittelamerika	|10990	|2652689	|8800000000	|
107	|Japan	|Asien	|377835	|126549976	|2950000000000	|
108	|Jersey	|Europa	|116	|88915	|2200000000	|
109	|Jordanien	|Mittlerer Osten	|89213	|4998564	|16000000000	|
110	|Kasachstan	|Osteuropa	|2717300	|16733227	|54500000000	|
111	|Kenia	|Afrika	|582650	|30339770	|45100000000	|
112	|Kiribati	|Ozeanien	|717	|91985	|74000000	|
113	|Korea, Nord	|Asien	|120540	|21687550	|22600000000	|
114	|Korea, Süd	|Asien	|98480	|47470969	|625700000000	|
115	|Kuwait	|Mittlerer Osten	|17820	|1973572	|44800000000	|
116	|Kyrgyzstan	|Osteuropa	|198500	|4685230	|10300000000	|
117	|Laos	|Südostasien	|236800	|5497459	|7000000000	|
118	|Latvia	|Europa	|64589	|2404926	|9800000000	|
119	|Libanon	|Mittlerer Osten	|10400	|3578036	|16200000000	|
120	|Lesotho	|Afrika	|30355	|2143141	|4700000000	|
121	|Liberia	|Afrika	|111370	|3164156	|2850000000	|
122	|Libya	|Afrika	|1759540	|5115450	|39300000000	|
123	|Liechtenstein	|Europa	|160	|32207	|730000000	|
124	|Litauen	|Europa	|65200	|3620756	|17300000000	|
125	|Luxemburg	|Europa	|2586	|437389	|14700000000	|
126	|Macau	|Südostasien	|21	|445594	|7650000000	|
127	|Macedonia The Former Yugoslav Republic of	|Europa	|25333	|2041467	|7600000000	|
128	|Madagascar	|Afrika	|587040	|15506472	|11500000000	|
129	|Malawi	|Afrika	|118480	|10385849	|9400000000	|
130	|Malaysia	|Südostasien	|329750	|21793293	|229100000000	|
131	|Maldives	|Asien	|300	|301475	|540000000	|
132	|Mali	|Afrika	|1240000	|10685948	|8500000000	|
133	|Malta	|Europa	|316	|391670	|5	|
134	|Man Isle of	|Europa	|572	|73117	|1200000000	|
135	|Marshall Inseln	|Ozeanien	|181	|68126	|105000000	|
136	|Martinique	|Mittelamerika	|1100	|414516	|4240000000	|
137	|Mauritania	|Afrika	|1030700	|2667859	|4900000000	|
138	|Mauritius	|Welt	|1860	|1179368	|12300000000	|
139	|Mayotte	|Afrika	|374	|155911	|85000000	|
140	|Mexiko	|Nordamerika	|1972550	|100349766	|865500000000	|
141	|Micronesia, Federated States of	|Ozeanien	|702	|133144	|240000000	|
142	|Moldova	|Osteuropa	|33843	|4430654	|9700000000	|
143	|Monaco	|Europa	|1	|31693	|870000000	|
144	|Mongolei	|Asien	|1565000	|2650952	|6100000000	|
145	|Montserrat	|Mittelamerika	|100	|6409	|31000000	|
146	|Marocco	|Afrika	|446550	|30122350	|108000000000	|
147	|Mozambique	|Afrika	|801590	|19104696	|18700000000	|
148	|Namibia	|Afrika	|825418	|1771327	|7100000000	|
149	|Nauru	|Ozeanien	|21	|11845	|100000000	|
150	|Nepal	|Asien	|140800	|24702119	|27400000000	|
151	|Niederlande	|Europa	|41532	|15892237	|365100000000	|
152	|Niederländische Antillen	|Mittelamerika	|960	|210134	|2400000000	|
153	|New Caledonia	|Ozeanien	|19060	|201816	|3000000000	|
154	|Neuseeland	|Ozeanien	|268680	|3819762	|63800000000	|
155	|Nicaragua	|Mittelamerika	|129494	|4812569	|12500000000	|
156	|Niger	|Afrika	|1267000	|10075511	|9600000000	|
157	|Nigeria	|Afrika	|923768	|123337822	|110500000000	|
158	|Niue	|Ozeanien	|260	|2113	|4500000	|
159	|Norfolk Island	|Ozeanien	|34	|1892	|None	|
160	|Northern Mariana Islands	|Ozeanien	|477	|71912	|524000000	|
161	|Norwegen	|Europa	|324220	|4481162	|111300000000	|
162	|Oman	|Mittlerer Osten	|212460	|2533389	|19600000000	|
163	|Pakistan	|Asien	|803940	|141553775	|282000000000	|
164	|Palau	|Ozeanien	|458	|18766	|160000000	|
165	|Panama	|Mittelamerika	|78200	|2808268	|21000000000	|
166	|Papua Neu Guinea	|Ozeanien	|462840	|4926984	|11600000000	|
167	|Paraguay	|Südamerika	|406750	|5585828	|19900000000	|
168	|Peru	|Südamerika	|1280000	|27012899	|116000000000	|
169	|Philippinen	|Südostasien	|300000	|81159644	|282000000000	|
170	|Pitcairn Islands	|Ozeanien	|47	|54	|None	|
171	|Polen	|Europa	|312685	|38646023	|276500000000	|
172	|Portugal	|Europa	|92391	|10048232	|151400000000	|
173	|Puerto Rico	|Mittelamerika	|9104	|3915798	|38100000000	|
174	|Qatar	|Mittlerer Osten	|11437	|744483	|12300000000	|
175	|Rum„nien	|Europa	|237500	|22411121	|87400000000	|
176	|Russland	|Asien	|17075200	|146001176	|620300000000	|
177	|Rwanda	|Afrika	|26338	|7229129	|5900000000	|
178	|Saint Helena	|Afrika	|410	|7212	|13900000	|
179	|Saint Kitts und Nevis	|Mittelamerika	|261	|38819	|244000000	|
180	|Saint Lucia	|Mittelamerika	|620	|156260	|656000000	|
181	|Saint Pierre und Miquelon	|Nordamerika	|242	|6896	|74000000	|
182	|Saint Vincent und die Grenadines	|Mittelamerika	|389	|115461	|309000000	|
183	|Samoa	|Ozeanien	|2860	|179466	|485000000	|
184	|San Marino	|Europa	|60	|26937	|500000000	|
185	|Sao Tome und Principe	|Afrika	|1001	|159883	|169000000	|
186	|Saudi-Arabien	|Mittlerer Osten	|1960582	|22023506	|191000000000	|
187	|Senegal	|Afrika	|196190	|9987494	|16600000000	|
188	|Serbien und Montenegro	|Europa	|102350	|10662087	|20600000000	|
189	|Seychellen	|Afrika	|455	|79326	|590000000	|
190	|Sierra Leone	|Afrika	|71740	|5232624	|2500000000	|
191	|Singapur	|Südostasien	|647	|4151264	|98000000000	|
192	|Slowakei	|Europa	|48845	|5407956	|45900000000	|
193	|Slowenien	|Europa	|20253	|1927593	|21400000000	|
194	|Solomon Islands	|Ozeanien	|28450	|466194	|1210000000	|
195	|Somalia	|Afrika	|637657	|7253137	|4300000000	|
196	|SüdAfrika	|Afrika	|1219912	|43421021	|296100000000	|
197	|Spanien	|Europa	|504782	|39996671	|677500000000	|
198	|Sri Lanka	|Asien	|65610	|19238575	|50500000000	|
199	|Sudan	|Afrika	|2505810	|35079814	|32600000000	|
200	|Suriname	|Südamerika	|163270	|431303	|1480000000	|
201	|Svalbard	|Arktik-Region	|62049	|2416	|None	|
202	|Swaziland	|Afrika	|17363	|1083289	|4200000000	|
203	|Schweden	|Europa	|449964	|8873052	|184000000000	|
204	|Schweiz	|Europa	|41290	|7262372	|197000000000	|
205	|Syrien	|Mittlerer Osten	|185180	|16305659	|42200000000	|
206	|Taiwan	|Südostasien	|35980	|22191087	|357000000000	|
207	|Tajikistan	|Osteuropa	|143100	|6440732	|6200000000	|
208	|Tanzania	|Afrika	|945087	|35306126	|23300000000	|
209	|Thailand	|Südostasien	|514000	|61230874	|388700000000	|
210	|Togo	|Afrika	|56785	|5018502	|8600000000	|
211	|Tokelau	|Ozeanien	|10	|1458	|1500000	|
212	|Tonga	|Ozeanien	|748	|102321	|238000000	|
213	|Trinidad und Tobago	|Mittelamerika	|5128	|1175523	|9410000000	|
214	|Tunesien	|Mittlerer Osten	|163610	|9593402	|52600000000	|
215	|Türkei	|Europa	|780580	|65666677	|409400000000	|
216	|Turkmenistan	|Osteuropa	|488100	|4518268	|7700000000	|
217	|Turks and Caicos Inseln	|Mittelamerika	|430	|17502	|117000000	|
218	|Tuvalu	|Ozeanien	|26	|10838	|7800000	|
219	|Uganda	|Afrika	|236040	|23317560	|24200000000	|
220	|Ukraine	|Osteuropa	|603700	|49153027	|109500000000	|
221	|Vereinigte Arabische Emirate	|Mittlerer Osten	|82880	|2369153	|41500000000	|
222	|Groß-Britannien	|Europa	|244820	|59511464	|1290000000000	|
223	|Vereinigte Staaten von Amerika	|Nordamerika	|9629091	|275562673	|9255000000000	|
224	|Uruguay	|Südamerika	|176220	|3334074	|28000000000	|
225	|Uzbekistan	|Osteuropa	|447400	|24755519	|59300000000	|
226	|Vanuatu	|Ozeanien	|14760	|189618	|245000000	|
227	|Venezuela	|Südamerika	|912050	|23542649	|182800000000	|
228	|Vietnam	|Südostasien	|329560	|78773873	|143100000000	|
229	|Virgin Islands	|Mittelamerika	|352	|120917	|1800000000	|
230	|Wallis und Futuna	|Ozeanien	|274	|15283	|28700000	|
231	|West Bank	|Mittlerer Osten	|5860	|2020298	|3300000000	|
232	|Westliche Sahara	|Afrika	|266000	|244943	|None	|
233	|Jemen	|Mittlerer Osten	|527970	|17479206	|12700000000	|
234	|Zambia	|Afrika	|752614	|9582418	|8500000000	|
235	|Zimbabwe	|Afrika	|390580	|11342521	|26500000000	|

In [9]:
result = con.execute("""
SELECT DISTINCT(Region)
FROM cia
""").fetchall()

for row in result:
    print(row[0])

Asien
Europa
Afrika
Ozeanien
Mittelamerika
Antarktis
Südamerika
Osteuropa
Mittlerer Osten
Nordamerika
Südostasien
Welt
Arktik-Region

## Besser mit Pandas
mit schöneren Ausgabetabellen 
Aufgabe: Versuche das Gleiche mit Pandas, was du von SQL kennst ;)

In [10]:
import pandas as pd

In [11]:
result = con.execute("SELECT * FROM cia").fetchall()
pd.DataFrame(result)

,0,1,2,3,4,5
0,1,Afghanistan,Asien,652000,25838797.0,2.100000e+10
1,2,Albanien,Europa,28748,3490435.0,5.600000e+09
2,3,Algerien,Afrika,2381740,31193917.0,1.476000e+11
3,4,Amerikanische Samoa-Inseln,Ozeanien,199,65446.0,1.500000e+08
4,5,Andorra,Europa,468,66824.0,1.200000e+09
...,...,...,...,...,...,...
230,231,West Bank,Mittlerer Osten,5860,2020298.0,3.300000e+09
231,232,Westliche Sahara,Afrika,266000,244943.0,NaN
232,233,Jemen,Mittlerer Osten,527970,17479206.0,1.270000e+10
233,234,Zambia,Afrika,752614,9582418.0,8.500000e+09
234,235,Zimbabwe,Afrika,390580,11342521.0,2.650000e+10

In [12]:
erg = pd.read_sql("SELECT * FROM cia", con)
erg

,LID,Name,Region,Flaeche,Einwohner,BIP
0,1,Afghanistan,Asien,652000,25838797.0,2.100000e+10
1,2,Albanien,Europa,28748,3490435.0,5.600000e+09
2,3,Algerien,Afrika,2381740,31193917.0,1.476000e+11
3,4,Amerikanische Samoa-Inseln,Ozeanien,199,65446.0,1.500000e+08
4,5,Andorra,Europa,468,66824.0,1.200000e+09
...,...,...,...,...,...,...
230,231,West Bank,Mittlerer Osten,5860,2020298.0,3.300000e+09
231,232,Westliche Sahara,Afrika,266000,244943.0,NaN
232,233,Jemen,Mittlerer Osten,527970,17479206.0,1.270000e+10
233,234,Zambia,Afrika,752614,9582418.0,8.500000e+09
234,235,Zimbabwe,Afrika,390580,11342521.0,2.650000e+10

# Ergebnis speichern in Datei

In [13]:
erg.to_html("cia.html")
erg.to_markdown("cia.md")
erg.to_csv("cia.csv")
erg.to_json("cia.json")
erg.to_xml("cia.xml")

# SQL - Select mit Pandas

In [14]:
pd.read_sql("""
SELECT Name AS `Anzahl der Länder, die mit D beginnen`
FROM cia
WHERE Name LIKE "D%"
ORDER BY Name
""", con)

  Anzahl der Länder, die mit D beginnen
0                           Deutschland
1                              Djibouti
2                              Dominica
3               Dominikanische Republik
4                              Dänemark

## Group By

In [15]:
pd.read_sql("""
SELECT Region, COUNT(*) AS `Anzahl Länder`
FROM cia
GROUP BY region
""", con)

             Region  Anzahl Länder
0            Afrika             54
1         Antarktis              1
2     Arktik-Region              3
3             Asien             14
4            Europa             44
5     Mittelamerika             30
6   Mittlerer Osten             17
7       Nordamerika              5
8         Osteuropa             11
9          Ozeanien             25
10       Südamerika             14
11      Südostasien             15
12             Welt              2

## Group By Having

In [16]:
pd.read_sql("""
SELECT Region, COUNT(*) AS `Anzahl Länder`
FROM cia
GROUP BY region
HAVING `Anzahl Länder` < 10
""", con)

          Region  Anzahl Länder
0      Antarktis              1
1  Arktik-Region              3
2    Nordamerika              5
3           Welt              2

# SELECT FROM WHERE GROUP BY HAVING ORDER BY LIMIT
an einem Beispiel

In [17]:
pd.read_sql("""
SELECT Region, COUNT(*) AS `Anzahl Länder`
FROM cia
WHERE Region IS NOT "Welt"
GROUP BY region
HAVING `Anzahl Länder` BETWEEN 10 AND 20
ORDER BY `Anzahl Länder`
LIMIT 2
""", con)

      Region  Anzahl Länder
0  Osteuropa             11
1      Asien             14